# Boilerplate code generated by OVITO Pro 3.8.4
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *


# Data import:
pipeline = import_file('/Users/ruhe/Desktop/ga2o3/relaxed-cell/slice_alpha', atom_style = 'atomic')

# Affine transformation:
pipeline.modifiers.append(AffineTransformationModifier(transformation = [[0.8746197071393957, -0.48480962024633706, 0.0, -5.8], [0.48480962024633706, 0.8746197071393957, 0.0, 3.2000000000000006], [0.0, 0.0, 1.0, 0.0]]))

export_file(pipeline, "/Users/ruhe/Desktop/slice_alpha", "lammps/data")
